### ISSUE TITLE
Update list of timezone aliases

### ISSUE THREAD

**Issue by tk3369** [Humans-of-Julia/HoJBot.jl#15]
For the timezone convertor utility:
Ideally, we just need a few timezone aliases that work for most people.

The current list is arbitrary for demo purpose.
We should update it with a better list.

https://github.com/Humans-of-Julia/HoJBot.jl/blob/800578f7b7aa9f531cdec9a32f99faf1a92d21dc/src/command/tz.jl#L1-L6

**Comment by AhmedsAxioms** [comment]
how would i contribute an update to the list, so I can add a few more Asian/African based timezones 😅

**Comment by Azzaare** [comment]
I think the idea is to provide aliases for existing time zones. Assume there is a timezone "Asia/Tokyo", but someone that lives in Kyoto wants the Kyoto alias.
Maybe we could add:
```julia
 CITY_ALIASES = Dict( 
     "LA" => "America/Los_Angeles", 
     "NY" => "America/New_York", 
     "Rio" => "America/Fortaleza", 
     "Brussels" => "Europe/Brussels", 
     "Tokyo" => "Asia/Tokyo", 
     "Kyoto" => "Asia/Tokyo", 
 ) 
```

But that is just my guess. Probably @tk3369 can say more about it :)

**Comment by AhmedsAxioms** [comment]
ahh i see well i'll wait for @tk3369  to talk more on it, before I fork and attempt the fix unless someone has done it already.

**Comment by tk3369** [comment]
Hi @abughurab16, Sorry for being late. I haven't seen this note until now :-) I'm OK if you want to add whatever you need to the list. I would avoid duplicates though because it could make the list very long and it does not add too much value.

P.S. Actually, I am just thinking about revamping the tz interface. I will try to write that up as a separate issue.

**Comment by tk3369** [comment]
See #95
