### ISSUE TITLE
Make reaction bot optional (either opt-in or opt-out is fine)

### ISSUE THREAD

**Issue by ScottPJones** [Humans-of-Julia/HoJBot.jl#18]
I don't like having non-human responses to my messages - I really only want to see responses from real Humans of Julia!

**Comment by rmsrosa** [comment]
I agree, and I prefer opt-in.

**Comment by tk3369** [comment]
I'm unsure which option is best:
1. Make it react by default and let people opt-out
2. Make it silent by default and let people opt-in

Perhaps run a poll with the community?

**Comment by Azzaare** [comment]
I am very slowly working on this. Originally for the game master command, but it should be extendable to any other thing.

**Comment by Azzaare** [comment]
The feature is done (for any service actually) in #32

**Comment by rmsrosa** [comment]
Closing this considering @Azzaare  implemented a solution.
