### ISSUE TITLE
Adding some packages to HoJBot env for documentation

### ISSUE THREAD

**Issue by Azzaare** [Humans-of-Julia/HoJBot.jl#27]
I think a lot of members are looking for documentation that is not from Base.
A currated list of packages to be added to HoJBot env would help.

- InteractiveUtils which bring many functions into REPL and other interactive IDE
- Probably most of HoJ packages as a principle 
- DataFrames and CSV were mentioned too

Feel free to add some more that makes sense and we can make a PR for it

**Comment by tk3369** [comment]
Discussions here https://github.com/Humans-of-Julia/HoJBot.jl/discussions/25
