### ISSUE TITLE
Making the bot able to open and close channels

### ISSUE THREAD

**Issue by Azzaare** [Humans-of-Julia/HoJBot.jl#33]
I would like to have the bot able to create and close temporary channels on a per-user basis.
For instance, assume one user wants to play a hojbot game for a while on day d.
He could ask for a personal game "channel" to be opened for some time (let's say an hour).

We could make the channel permanent, but I am not sure the channel can be hidden from the mods, which would make it pretty noisy.

Anyway, it could be useful for other circumstances, what do you think?

**Comment by tk3369** [comment]
My only concern is the potential of being abused, or to a lesser extent people forgetting to delete the temp channel. 

Perhaps it would be best to integrate with the game foe whatever it is needed? Then you can manage the lifecycle and destroy it automatically when it's no longer needed.
