### ISSUE TITLE
Time zone to convert to

### ISSUE THREAD

**Issue by rmsrosa** [Humans-of-Julia/HoJBot.jl#5]
It seems we need another argument in `tz convert <date_time_spec>` to tell the bot which time zone(s) to convert the `date_time_spec` to. Maybe `tz convert <date_time_spec> <target_time_zones>...`

If empty, it can take the current default cities. Or, if possible, it can try to infer the time-zone of the user issuing the command.

And we can dd some special aliases, like `mods`, `grakln`, so it converts to the time-zone of all the mods or of all the people involved in a project.

**Comment by tk3369** [comment]
The intended usage of the `tz` command is to communicate clearly to everyone what a meeting time is. 

We had a couple of meetings (mod meeting, grakn meeting, etc.) and people come from various timezones, making it difficult to understand each other what the exact meeting time is.

I don't mind making it a more general converter and provide more functionalities. As usual, PRs are welcome!

**Comment by tk3369** [comment]
Closing this issue. See new proposed changes at #95
